### ISSUE TITLE
Wren as submodule

### ISSUE THREAD

**Issue by kmarekspartz** [zeckalpha/wren-io#1]
Until wren has support for packaging/modules, I think we'll use git to import wren proper.

**Comment by munificent** [comment]
I've heard Git submodules can be kind of a pain, though I don't know the details. Another option is to just manually copy the Wren source code into this and update it periodically. Whatever you think works the best.

**Comment by kmarekspartz** [comment]
What about relying on wren being an adjacent directory? That might mitigate some of the manual copying issues and eliminate the submodule issues. And again, that would just be temporary until packaging / module support.

**Comment by munificent** [comment]
Sure, whatever keeps you moving quickly!
