### ISSUE TITLE
Can't build against mainline Wren

### ISSUE THREAD

**Issue by gsmaverick** [zeckalpha/wren-io#11]
This project no longer seems to build against Wren when running `make` post-checkout.

**Comment by kmarekspartz** [comment]
Sorry about that! I've fallen a bit behind haven't I. I'll take a look at this.

**Comment by kmarekspartz** [comment]
We're reconsidering this being a separate repo; stay tuned.

**Comment by brandly** [comment]
What's the state of this project?

**Comment by munificent** [comment]
We're starting to work on accomplishing this in the main Wren repo. That's what the [libuv](https://github.com/munificent/wren/tree/libuv) branch is the first step towards.

**Comment by kmarekspartz** [comment]
Cool to hear!

**Comment by brandly** [comment]
Excellent!
