### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by kmarekspartz** [zeckalpha/wren-io#3]
See munificent/wren#29

**Comment by gsmaverick** [comment]
What are you thinking about adding here? Just more basic collection types or something more expansive?

**Comment by kmarekspartz** [comment]
Start with basic collections, then something more expansive. I put in the pure-wren Set example upstream. Once Maps are in upstream, we should think about Sequence / Collection root classes / interfaces.

**Comment by kmarekspartz** [comment]
See #11
