### ISSUE TITLE
Time Methods

### ISSUE THREAD

**Issue by gsmaverick** [zeckalpha/wren-io#6]
Noting some ideas around supporting basic time methods. Something along the lines of:

``` dart
class Time {
  static now { ... }
  static sleep (seconds) { ... }
  static usertime { ... }
  static systemtime { ... }
}
```

Obviously this doesn't capture the full cornucopia of date & time operations but it would be a good start.

**Comment by kmarekspartz** [comment]
Classes for points in time, lengths of time, time intervals.

**Comment by kmarekspartz** [comment]
See #11
