### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gsmaverick** [zeckalpha/wren-io#7]
It would be nice to have a built-in logging facility.

**Comment by kmarekspartz** [comment]
How's an API like this?

``` dart
class LogLevel {}
class Error is LogLevel {}
class Warning is LogLevel {}
class Info is LogLevel {}
class Debug is LogLevel {}

class LogMessage {
  _level
  _time
  _content
}

class LogFormatter {
  format(message)
}

class LogHandler {
  _formatter
  handle(message)
}

class Logger {
  _handler
  log(string)
  log(level, string)
  error(string)
  // ...
}
```

**Comment by munificent** [comment]
I've personally never found a set of logging levels that fit all of my use cases. Maybe just make it a string and provide a few constants for common ones? Then if those don't fit a user's needs, they can define their own too.

**Comment by kmarekspartz** [comment]
What about defining toString on base to be self.class.name.uppercase? That
allows for new log levels. The only issue I can think of is how to maintain
the ordered-set property.

**Comment by kmarekspartz** [comment]
See #11

**Comment by zeckalpha** [comment]
See #11
