### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by gsmaverick** [zeckalpha/wren-io#8]
It would be nice to have a testing framework written in Wren to write tests for all the batteries we're including with wren-io. I've hacked around a bit on a framework that would be similar to [Jasmine](http://jasmine.github.io/2.1/introduction.html) or [Mocha](http://mochajs.org/).

**Comment by kmarekspartz** [comment]
Great! I was thinking of adding features until the subset of Python used
for the test.py file, and then translating that, but I'd like to see what
you have.

**Comment by gsmaverick** [comment]
```dart

```

**Comment by gsmaverick** [comment]
Roughly along the lines of this:

``` dart
var suite = new Suite("truth", new Fn { |s|
  s.it("should return true", new Fiber {
    s.expect(true).toBeTrue
    s.expect(true).not.toBeFalse
  })
}
```

Using Fibers for the `it` body has a number of cool features:
- The entire test suite doesn't fail if there's a runtime error inside of an `it`.
- Simpler data model for `it` bodies with multiple `expect`s that relies on less mutable state. Each `expect` can call `Fiber.yield` to let the suite runner know the result and then the runner can keep track of whether all the expectations were passed in a suite.
- It supports asynchronous operations of out the box, no modifications required.

**Comment by gsmaverick** [comment]
See: https://gist.github.com/gsmaverick/e0a2b9424d507b3a8faf for a simple implementation of this. Obviously we'd want to build out the functionality of `expect` a lot more but I have some ideas around that.

**Comment by kmarekspartz** [comment]
Neat!

I have a couple suggestions for syntax.

Instead of new Fn, does a block work?

Similarly, can a block be passed in and get passed along to new Fiber? That
looks a bit redundant to be called every time.

**Comment by gsmaverick** [comment]
Good suggestions, I wasn't aware of that block as the last argument pattern but that significantly cleaned up the resulting tests code which you can see here: https://gist.github.com/gsmaverick/6715d5c98d4a8be3977b

Thoughts?

**Comment by kmarekspartz** [comment]
Great!

**Comment by kmarekspartz** [comment]
I would add a method `expect_fiber`:

``` dart
class Suite {
  // ...
  expect_fiber(block) {
    return expect(new Fiber(block))
  }
}
```

``` dart
// ...
s.expect_fiber({ "foo".contains(1) }).toBeARuntimeError("Argument must be a String.")
```

Ideally the parens around the block could go away, but I don't think that's possible with the current grammar.

**Comment by gsmaverick** [comment]
I've started experimenting with a testing framework, see: https://github.com/gsmaverick/wren-test

**Comment by kmarekspartz** [comment]
Great! I'll probably 'include' it somehow. Need to figure out the best way to do that... I've not had much time lately for this. Want to take a crack at that?

**Comment by kmarekspartz** [comment]
Hmm, I like how you're doing deps in that repo. I'll set this up similarly.

**Comment by munificent** [comment]
> Ideally the parens around the block could go away, but I don't think that's possible with the current grammar.

It should be. :)

For example, this works fine:

``` dart
class Foo {
  static bar(block) { 123 }
}

IO.print(Foo.bar { null }.toString) // <--
```

**Comment by kmarekspartz** [comment]
See #11
